{
    'name': 'GMLeave Master',
    'version': '0.1',
    'author': 'Greenmount',
    'website': 'http://www.greenmount.co.th/gmleave',
    'category': 'Custom',
    'depends': ['base', 'muk_web_theme', 'web_widget_timepicker', 'queue_job'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/department_data.xml',
        'data/position_data.xml',
        'data/leave_type_data.xml',
        'data/employee_type_data.xml',
        'data/holiday_data.xml',
        'views/menu.xml',
        'views/department_view.xml',
        'views/position_view.xml',
        'views/leave_type_view.xml',
        'views/employee_view.xml',
        'views/holiday_view.xml',
        'views/employee_type_view.xml',
        'wizard/approve_resign_wizard.xml',
    ],
    'demo': [],
}
