{
    'name': 'GMOT Master',
    'summary': 'Greenmount OT Calculation & Payments',
    'version': '0.1',
    'author': 'Appcode Technology',
    'website': 'http://appcode.co.th/gmot',
    'category': 'Custom',
    'depends': ['base', 'gmleave_master'],
    'data': [
        'security/security.xml',
        'templates/layouts.xml',
        'templates/index.xml',
        'templates/report.xml',
        'templates/salary.xml',
        'templates/config.xml',
        'templates/ot_approve.xml',
        'templates/ot_approve_draft.xml',
        'templates/ot_approve_history.xml',
        'templates/ot_jobs.xml',
        'templates/ot_open.xml',
    ],
    'demo': [],
}
